const letters = [
	'A',
	'B',
	'C',
	'D',
	'E',
	'F',
	'G',
	'H',
	'I',
	'J',
	'K',
	'L',
	'M',
	'N',
	'O',
	'P',
	'Q',
	'R',
	'S',
	'T',
	'U',
	'V',
	'W',
	'X',
	'Y',
	'Z',
]

const states = [
	{ label: 'Alabama', value: 'AL' },
	{ label: 'Alaska', value: 'AK' },
	{ label: 'Arizona', value: 'AZ' },
	{ label: 'Arkansas', value: 'AR' },
	{ label: 'California', value: 'CA' },
	{ label: 'Colorado', value: 'CO' },
	{ label: 'Connecticut', value: 'CT' },
	{ label: 'Delaware', value: 'DE' },
	{ label: 'District Of Columbia', value: 'DC' },
	{ label: 'Florida', value: 'FL' },
	{ label: 'Georgia', value: 'GA' },
	{ label: 'Hawaii', value: 'HI' },
	{ label: 'Idaho', value: 'ID' },
	{ label: 'Illinois', value: 'IL' },
	{ label: 'Indiana', value: 'IN' },
	{ label: 'Iowa', value: 'IA' },
	{ label: 'Kansas', value: 'KS' },
	{ label: 'Kentucky', value: 'KY' },
	{ label: 'Louisiana', value: 'LA' },
	{ label: 'Maine', value: 'ME' },
	{ label: 'Maryland', value: 'MD' },
	{ label: 'Massachusetts', value: 'MA' },
	{ label: 'Michigan', value: 'MI' },
	{ label: 'Minnesota', value: 'MN' },
	{ label: 'Mississippi', value: 'MS' },
	{ label: 'Missouri', value: 'MO' },
	{ label: 'Montana', value: 'MT' },
	{ label: 'Nebraska', value: 'NE' },
	{ label: 'Nevada', value: 'NV' },
	{ label: 'New Hampshire', value: 'NH' },
	{ label: 'New Jersey', value: 'NJ' },
	{ label: 'New Mexico', value: 'NM' },
	{ label: 'New York', value: 'NY' },
	{ label: 'North Carolina', value: 'NC' },
	{ label: 'North Dakota', value: 'ND' },
	{ label: 'Ohio', value: 'OH' },
	{ label: 'Oklahoma', value: 'OK' },
	{ label: 'Oregon', value: 'OR' },
	{ label: 'Pennsylvania', value: 'PA' },
	{ label: 'Rhode Island', value: 'RI' },
	{ label: 'South Carolina', value: 'SC' },
	{ label: 'South Dakota', value: 'SD' },
	{ label: 'Tennessee', value: 'TN' },
	{ label: 'Texas', value: 'TX' },
	{ label: 'Utah', value: 'UT' },
	{ label: 'Vermont', value: 'VT' },
	{ label: 'Virginia', value: 'VA' },
	{ label: 'Washington', value: 'WA' },
	{ label: 'West Virginia', value: 'WV' },
	{ label: 'Wisconsin', value: 'WI' },
	{ label: 'Wyoming', value: 'WY' },
]

const countries = [
	{ label: 'Afghanistan', value: 'AF' },
	{ label: 'Albania', value: 'AL' },
	{ label: 'Algeria', value: 'DZ' },
	{ label: 'American Samoa', value: 'AS' },
	{ label: 'Andorra', value: 'AD' },
	{ label: 'Angola', value: 'AO' },
	{ label: 'Anguilla', value: 'AI' },
	{ label: 'Antarctica', value: 'AQ' },
	{ label: 'Antigua and Barbuda', value: 'AG' },
	{ label: 'Argentina', value: 'AR' },
	{ label: 'Armenia', value: 'AM' },
	{ label: 'Aruba', value: 'AW' },
	{ label: 'Australia', value: 'AU' },
	{ label: 'Austria', value: 'AT' },
	{ label: 'Azerbaijan', value: 'AZ' },
	{ label: 'Bahamas', value: 'BS' },
	{ label: 'Bahrain', value: 'BH' },
	{ label: 'Bangladesh', value: 'BD' },
	{ label: 'Barbados', value: 'BB' },
	{ label: 'Belarus', value: 'BY' },
	{ label: 'Belgium', value: 'BE' },
	{ label: 'Belize', value: 'BZ' },
	{ label: 'Benin', value: 'BJ' },
	{ label: 'Bermuda', value: 'BM' },
	{ label: 'Bhutan', value: 'BT' },
	{ label: 'Bolivia', value: 'BO' },
	{ label: 'Bosnia and Herzegovina', value: 'BA' },
	{ label: 'Botswana', value: 'BW' },
	{ label: 'Brazil', value: 'BR' },
	{ label: 'British Indian Ocean Territory', value: 'IO' },
	{ label: 'British Virgin Islands', value: 'VG' },
	{ label: 'Brunei', value: 'BN' },
	{ label: 'Bulgaria', value: 'BG' },
	{ label: 'Burkina Faso', value: 'BF' },
	{ label: 'Burundi', value: 'BI' },
	{ label: 'Cambodia', value: 'KH' },
	{ label: 'Cameroon', value: 'CM' },
	{ label: 'Canada', value: 'CA' },
	{ label: 'Cape Verde', value: 'CV' },
	{ label: 'Cayman Islands', value: 'KY' },
	{ label: 'Central African Republic', value: 'CF' },
	{ label: 'Chad', value: 'TD' },
	{ label: 'Chile', value: 'CL' },
	{ label: 'China', value: 'CN' },
	{ label: 'Christmas Island', value: 'CX' },
	{ label: 'Cocos Islands', value: 'CC' },
	{ label: 'Colombia', value: 'CO' },
	{ label: 'Comoros', value: 'KM' },
	{ label: 'Cook Islands', value: 'CK' },
	{ label: 'Costa Rica', value: 'CR' },
	{ label: 'Croatia', value: 'HR' },
	{ label: 'Cuba', value: 'CU' },
	{ label: 'Curacao', value: 'CW' },
	{ label: 'Cyprus', value: 'CY' },
	{ label: 'Czech Republic', value: 'CZ' },
	{ label: 'Democratic Republic of the Congo', value: 'CD' },
	{ label: 'Denmark', value: 'DK' },
	{ label: 'Djibouti', value: 'DJ' },
	{ label: 'Dominica', value: 'DM' },
	{ label: 'Dominican Republic', value: 'DO' },
	{ label: 'East Timor', value: 'TL' },
	{ label: 'Ecuador', value: 'EC' },
	{ label: 'Egypt', value: 'EG' },
	{ label: 'El Salvador', value: 'SV' },
	{ label: 'Equatorial Guinea', value: 'GQ' },
	{ label: 'Eritrea', value: 'ER' },
	{ label: 'Estonia', value: 'EE' },
	{ label: 'Ethiopia', value: 'ET' },
	{ label: 'Falkland Islands', value: 'FK' },
	{ label: 'Faroe Islands', value: 'FO' },
	{ label: 'Fiji', value: 'FJ' },
	{ label: 'Finland', value: 'FI' },
	{ label: 'France', value: 'FR' },
	{ label: 'French Polynesia', value: 'PF' },
	{ label: 'Gabon', value: 'GA' },
	{ label: 'Gambia', value: 'GM' },
	{ label: 'Georgia', value: 'GE' },
	{ label: 'Germany', value: 'DE' },
	{ label: 'Ghana', value: 'GH' },
	{ label: 'Gibraltar', value: 'GI' },
	{ label: 'Greece', value: 'GR' },
	{ label: 'Greenland', value: 'GL' },
	{ label: 'Grenada', value: 'GD' },
	{ label: 'Guam', value: 'GU' },
	{ label: 'Guatemala', value: 'GT' },
	{ label: 'Guernsey', value: 'GG' },
	{ label: 'Guinea', value: 'GN' },
	{ label: 'Guinea-Bissau', value: 'GW' },
	{ label: 'Guyana', value: 'GY' },
	{ label: 'Haiti', value: 'HT' },
	{ label: 'Honduras', value: 'HN' },
	{ label: 'Hong Kong', value: 'HK' },
	{ label: 'Hungary', value: 'HU' },
	{ label: 'Iceland', value: 'IS' },
	{ label: 'India', value: 'IN' },
	{ label: 'Indonesia', value: 'ID' },
	{ label: 'Iran', value: 'IR' },
	{ label: 'Iraq', value: 'IQ' },
	{ label: 'Ireland', value: 'IE' },
	{ label: 'Isle of Man', value: 'IM' },
	{ label: 'Israel', value: 'IL' },
	{ label: 'Italy', value: 'IT' },
	{ label: 'Ivory Coast', value: 'CI' },
	{ label: 'Jamaica', value: 'JM' },
	{ label: 'Japan', value: 'JP' },
	{ label: 'Jersey', value: 'JE' },
	{ label: 'Jordan', value: 'JO' },
	{ label: 'Kazakhstan', value: 'KZ' },
	{ label: 'Kenya', value: 'KE' },
	{ label: 'Kiribati', value: 'KI' },
	{ label: 'Kosovo', value: 'XK' },
	{ label: 'Kuwait', value: 'KW' },
	{ label: 'Kyrgyzstan', value: 'KG' },
	{ label: 'Laos', value: 'LA' },
	{ label: 'Latvia', value: 'LV' },
	{ label: 'Lebanon', value: 'LB' },
	{ label: 'Lesotho', value: 'LS' },
	{ label: 'Liberia', value: 'LR' },
	{ label: 'Libya', value: 'LY' },
	{ label: 'Liechtenstein', value: 'LI' },
	{ label: 'Lithuania', value: 'LT' },
	{ label: 'Luxembourg', value: 'LU' },
	{ label: 'Macau', value: 'MO' },
	{ label: 'Macedonia', value: 'MK' },
	{ label: 'Madagascar', value: 'MG' },
	{ label: 'Malawi', value: 'MW' },
	{ label: 'Malaysia', value: 'MY' },
	{ label: 'Maldives', value: 'MV' },
	{ label: 'Mali', value: 'ML' },
	{ label: 'Malta', value: 'MT' },
	{ label: 'Marshall Islands', value: 'MH' },
	{ label: 'Mauritania', value: 'MR' },
	{ label: 'Mauritius', value: 'MU' },
	{ label: 'Mayotte', value: 'YT' },
	{ label: 'Mexico', value: 'MX' },
	{ label: 'Micronesia', value: 'FM' },
	{ label: 'Moldova', value: 'MD' },
	{ label: 'Monaco', value: 'MC' },
	{ label: 'Mongolia', value: 'MN' },
	{ label: 'Montenegro', value: 'ME' },
	{ label: 'Montserrat', value: 'MS' },
	{ label: 'Morocco', value: 'MA' },
	{ label: 'Mozambique', value: 'MZ' },
	{ label: 'Myanmar', value: 'MM' },
	{ label: 'Namibia', value: 'NA' },
	{ label: 'Nauru', value: 'NR' },
	{ label: 'Nepal', value: 'NP' },
	{ label: 'Netherlands', value: 'NL' },
	{ label: 'Netherlands Antilles', value: 'AN' },
	{ label: 'New Caledonia', value: 'NC' },
	{ label: 'New Zealand', value: 'NZ' },
	{ label: 'Nicaragua', value: 'NI' },
	{ label: 'Niger', value: 'NE' },
	{ label: 'Nigeria', value: 'NG' },
	{ label: 'Niue', value: 'NU' },
	{ label: 'North Korea', value: 'KP' },
	{ label: 'Northern Mariana Islands', value: 'MP' },
	{ label: 'Norway', value: 'NO' },
	{ label: 'Oman', value: 'OM' },
	{ label: 'Pakistan', value: 'PK' },
	{ label: 'Palau', value: 'PW' },
	{ label: 'Palestine', value: 'PS' },
	{ label: 'Panama', value: 'PA' },
	{ label: 'Papua New Guinea', value: 'PG' },
	{ label: 'Paraguay', value: 'PY' },
	{ label: 'Peru', value: 'PE' },
	{ label: 'Philippines', value: 'PH' },
	{ label: 'Pitcairn', value: 'PN' },
	{ label: 'Poland', value: 'PL' },
	{ label: 'Portugal', value: 'PT' },
	{ label: 'Puerto Rico', value: 'PR' },
	{ label: 'Qatar', value: 'QA' },
	{ label: 'Republic of the Congo', value: 'CG' },
	{ label: 'Reunion', value: 'RE' },
	{ label: 'Romania', value: 'RO' },
	{ label: 'Russia', value: 'RU' },
	{ label: 'Rwanda', value: 'RW' },
	{ label: 'Saint Barthelemy', value: 'BL' },
	{ label: 'Saint Helena', value: 'SH' },
	{ label: 'Saint Kitts and Nevis', value: 'KN' },
	{ label: 'Saint Lucia', value: 'LC' },
	{ label: 'Saint Martin', value: 'MF' },
	{ label: 'Saint Pierre and Miquelon', value: 'PM' },
	{ label: 'Saint Vincent and the Grenadines', value: 'VC' },
	{ label: 'Samoa', value: 'WS' },
	{ label: 'San Marino', value: 'SM' },
	{ label: 'Sao Tome and Principe', value: 'ST' },
	{ label: 'Saudi Arabia', value: 'SA' },
	{ label: 'Senegal', value: 'SN' },
	{ label: 'Serbia', value: 'RS' },
	{ label: 'Seychelles', value: 'SC' },
	{ label: 'Sierra Leone', value: 'SL' },
	{ label: 'Singapore', value: 'SG' },
	{ label: 'Sint Maarten', value: 'SX' },
	{ label: 'Slovakia', value: 'SK' },
	{ label: 'Slovenia', value: 'SI' },
	{ label: 'Solomon Islands', value: 'SB' },
	{ label: 'Somalia', value: 'SO' },
	{ label: 'South Africa', value: 'ZA' },
	{ label: 'South Korea', value: 'KR' },
	{ label: 'South Sudan', value: 'SS' },
	{ label: 'Spain', value: 'ES' },
	{ label: 'Sri Lanka', value: 'LK' },
	{ label: 'Sudan', value: 'SD' },
	{ label: 'Suriname', value: 'SR' },
	{ label: 'Svalbard and Jan Mayen', value: 'SJ' },
	{ label: 'Swaziland', value: 'SZ' },
	{ label: 'Sweden', value: 'SE' },
	{ label: 'Switzerland', value: 'CH' },
	{ label: 'Syria', value: 'SY' },
	{ label: 'Taiwan', value: 'TW' },
	{ label: 'Tajikistan', value: 'TJ' },
	{ label: 'Tanzania', value: 'TZ' },
	{ label: 'Thailand', value: 'TH' },
	{ label: 'Togo', value: 'TG' },
	{ label: 'Tokelau', value: 'TK' },
	{ label: 'Tonga', value: 'TO' },
	{ label: 'Trinidad and Tobago', value: 'TT' },
	{ label: 'Tunisia', value: 'TN' },
	{ label: 'Turkey', value: 'TR' },
	{ label: 'United Arab Emirates', value: 'AE' },
	{ label: 'United Kingdom', value: 'GB' },
	{ label: 'United States', value: 'US' },
	{ label: 'Uruguay', value: 'UY' },
	{ label: 'Uzbekistan', value: 'UZ' },
	{ label: 'Vanuatu', value: 'VU' },
	{ label: 'Vatican', value: 'VA' },
	{ label: 'Venezuela', value: 'VE' },
	{ label: 'Vietnam', value: 'VN' },
	{ label: 'Wallis and Futuna', value: 'WF' },
	{ label: 'Western Sahara', value: 'EH' },
	{ label: 'Yemen', value: 'YE' },
	{ label: 'Zambia', value: 'ZM' },
	{ label: 'Zimbabwe', value: 'ZW' },
]

const companies = [
	{ label: 'American Airlines', value: 'American Airlines' },
	{ label: 'Delta Airlines', value: 'Delta Airlines' },
	{ label: 'United Airlines', value: 'United Airlines' },
	{ label: 'Alaska Airlines', value: 'Alaska Airlines' },
	{ label: 'Frontier Airlines', value: 'Frontier Airlines' },
	{ label: 'Hawaiian Airlines', value: 'Hawaiian Airlines' },
	{ label: 'JetBlue', value: 'JetBlue' },
	{ label: 'Southwest Airlines', value: 'Southwest Airlines' },
	{ label: 'Atlas', value: 'Atlas' },
	{ label: 'FreightRunners Express', value: 'FreightRunners Express' },
	{ label: 'Mountain Air Cargo', value: 'Mountain Air Cargo' },
	{ label: 'UPS', value: 'UPS' },
	{ label: 'Federal Express', value: 'Federal Express' },
	{ label: 'Avelo', value: 'Avelo' },
	{ label: 'Breeze Airways', value: 'Breeze Airways' },
	{ label: 'Spirit Airlines', value: 'Spirit Airlines' },
	{ label: 'Sun Country', value: 'Sun Country' },
	{ label: 'Air Choice One', value: 'Air Choice One' },
	{ label: 'Ameriflight', value: 'Ameriflight' },
	{ label: 'Ameristar', value: 'Ameristar' },
	{ label: 'Castle Aviation', value: 'Castle Aviation' },
	{ label: 'CSA Air', value: 'CSA Air' },
	{ label: 'Empire Airlines', value: 'Empire Airlines' },
	{ label: 'flyExclusive', value: 'flyExclusive' },
	{ label: 'Jet Linx', value: 'Jet Linx' },
	{ label: 'Justice Air', value: 'Justice Air' },
	{ label: 'Kalitta Charters', value: 'Kalitta Charters' },
	{ label: 'Key Lime Air', value: 'Key Lime Air' },
	{ label: 'Martinair', value: 'Martinair' },
	{ label: 'Moser Aviation', value: 'Moser Aviation' },
	{ label: 'NetJets', value: 'NetJets' },
	{ label: 'Plane Sense', value: 'Plane Sense' },
	{ label: 'Sierra West Airlines', value: 'Sierra West Airlines' },
	{ label: 'Silverhawk Aviation', value: 'Silverhawk Aviation' },
	{ label: 'STA Jets', value: 'STA Jets' },
	{ label: 'TradeWind Aviation', value: 'TradeWind Aviation' },
	{
		label: 'West Coast Aviation Services',
		value: 'West Coast Aviation Services',
	},
	{ label: 'Wheels Up', value: 'Wheels Up' },
	{ label: 'XOJet', value: 'XOJet' },
	{ label: 'Air Wisconsin', value: 'Air Wisconsin' },
	{ label: 'CommuteAir', value: 'CommuteAir' },
	{ label: 'Cape Air', value: 'Cape Air' },
	{ label: 'Endeavor Air', value: 'Endeavor Air' },
	{ label: 'Envoy Air', value: 'Envoy Air' },
	{ label: 'GoJet Airlines', value: 'GoJet Airlines' },
	{ label: 'Horizon Air', value: 'Horizon Air' },
	{ label: 'JSX', value: 'JSX' },
	{ label: 'Mesa Airlines', value: 'Mesa Airlines' },
	{ label: 'Peninsula Airways', value: 'Peninsula Airways' },
	{ label: 'Piedmont', value: 'Piedmont' },
	{ label: 'PSA Airlines', value: 'PSA Airlines' },
	{ label: 'Republic Airways', value: 'Republic Airways' },
	{ label: 'Skywest Airlines', value: 'Skywest Airlines' },
]

const airlines = [
	{
		category: 'Legacy',
		name: 'American Airlines',
		image: 'src/assets/americanAirlines.png',
		favorite: false,
	},
	{
		category: 'Legacy',
		name: 'Delta Airlines',
		image: 'src/assets/deltaAirlines.png',
		favorite: false,
	},
	{
		category: 'Legacy',
		name: 'United Airlines',
		image: 'src/assets/unitedAirlines.png',
		favorite: false,
	},
	{
		category: 'Major',
		name: 'Alaska Airlines',
		image: 'src/assets/americanAirlines.png',
		favorite: false,
	},
	{
		category: 'Major',
		name: 'Frontier Airlines',
		image: 'src/assets/americanAirlines.png',
		favorite: false,
	},
	{
		category: 'Major',
		name: 'Hawaiian Airlines',
		image: 'src/assets/americanAirlines.png',
		favorite: false,
	},
	{
		category: 'Major',
		name: 'JetBlue',
		image: 'src/assets/americanAirlines.png',
		favorite: false,
	},
	{
		category: 'Major',
		name: 'Southwest Airlines',
		image: 'src/assets/southwestAirlines.png',
		favorite: false,
	},
	{
		category: 'Cargo',
		name: 'Atlas',
		image: 'src/assets/americanAirlines.png',
		favorite: false,
	},
	{
		category: 'Cargo',
		name: 'FreightRunners Express',
		image: 'src/assets/americanAirlines.png',
		favorite: false,
	},
	{
		category: 'Cargo',
		name: 'Mountain Air Cargo',
		image: 'src/assets/americanAirlines.png',
		favorite: false,
	},
	{
		category: 'Cargo',
		name: 'UPS',
		image: 'src/assets/ups.png',
		favorite: false,
	},
	{
		category: 'Cargo',
		name: 'Federal Express',
		image: 'src/assets/fedex.png',
		favorite: false,
	},
	{
		category: 'National',
		name: 'Avelo',
		image: 'src/assets/americanAirlines.png',
		favorite: false,
	},
	{
		category: 'National',
		name: 'Breeze Airways',
		image: 'src/assets/americanAirlines.png',
		favorite: false,
	},
	{
		category: 'National',
		name: 'Spirit Airlines',
		image: 'src/assets/americanAirlines.png',
		favorite: false,
	},
	{
		category: 'National',
		name: 'Sun Country',
		image: 'src/assets/americanAirlines.png',
		favorite: false,
	},
	{
		category: 'Part 135',
		name: 'Air Choice One',
		image: 'src/assets/americanAirlines.png',
		favorite: false,
	},
	{
		category: 'Part 135',
		name: 'Ameriflight',
		image: 'src/assets/americanAirlines.png',
		favorite: false,
	},
	{
		category: 'Part 135',
		name: 'Ameristar',
		image: 'src/assets/americanAirlines.png',
		favorite: false,
	},
	{
		category: 'Part 135',
		name: 'Castle Aviation',
		image: 'src/assets/americanAirlines.png',
		favorite: false,
	},
	{
		category: 'Part 135',
		name: 'CSA Air',
		image: 'src/assets/americanAirlines.png',
		favorite: false,
	},
	{
		category: 'Part 135',
		name: 'Empire Airlines',
		image: 'src/assets/americanAirlines.png',
		favorite: false,
	},
	{
		category: 'Part 135',
		name: 'flyExclusive',
		image: 'src/assets/americanAirlines.png',
		favorite: false,
	},
	{
		category: 'Part 135',
		name: 'Jet Linx',
		image: 'src/assets/americanAirlines.png',
		favorite: false,
	},
	{
		category: 'Part 135',
		name: 'Justice Air',
		image: 'src/assets/americanAirlines.png',
		favorite: false,
	},
	{
		category: 'Part 135',
		name: 'Kalitta Charters',
		image: 'src/assets/americanAirlines.png',
		favorite: false,
	},
	{
		category: 'Part 135',
		name: 'Key Lime Air',
		image: 'src/assets/americanAirlines.png',
		favorite: false,
	},
	{
		category: 'Part 135',
		name: 'Martinair',
		image: 'src/assets/americanAirlines.png',
		favorite: false,
	},
	{
		category: 'Part 135',
		name: 'Moser Aviation',
		image: 'src/assets/americanAirlines.png',
		favorite: false,
	},
	{
		category: 'Part 135',
		name: 'NetJets',
		image: 'src/assets/americanAirlines.png',
		favorite: false,
	},
	{
		category: 'Part 135',
		name: 'Plane Sense',
		image: 'src/assets/americanAirlines.png',
		favorite: false,
	},
	{
		category: 'Part 135',
		name: 'Sierra West Airlines',
		image: 'src/assets/americanAirlines.png',
		favorite: false,
	},
	{
		category: 'Part 135',
		name: 'Silverhawk Aviation',
		image: 'src/assets/americanAirlines.png',
		favorite: false,
	},
	{
		category: 'Part 135',
		name: 'STA Jets',
		image: 'src/assets/americanAirlines.png',
		favorite: false,
	},
	{
		category: 'Part 135',
		name: 'TradeWind Aviation',
		image: 'src/assets/americanAirlines.png',
		favorite: false,
	},
	{
		category: 'Part 135',
		name: 'West Coast Aviation Services',
		image: 'src/assets/americanAirlines.png',
		favorite: false,
	},
	{
		category: 'Part 135',
		name: 'Wheels Up',
		image: 'src/assets/americanAirlines.png',
		favorite: false,
	},
	{
		category: 'Part 135',
		name: 'XOJet',
		image: 'src/assets/americanAirlines.png',
		favorite: false,
	},
	{
		category: 'Regional',
		name: 'Air Wisconsin',
		image: 'src/assets/americanAirlines.png',
		favorite: false,
	},
	{
		category: 'Regional',
		name: 'CommuteAir',
		image: 'src/assets/americanAirlines.png',
		favorite: false,
	},
	{
		category: 'Regional',
		name: 'Cape Air',
		image: 'src/assets/americanAirlines.png',
		favorite: false,
	},
	{
		category: 'Regional',
		name: 'Endeavor Air',
		image: 'src/assets/americanAirlines.png',
		favorite: false,
	},
	{
		category: 'Regional',
		name: 'Envoy Air',
		image: 'src/assets/americanAirlines.png',
		favorite: false,
	},
	{
		category: 'Regional',
		name: 'GoJet Airlines',
		image: 'src/assets/americanAirlines.png',
		favorite: false,
	},
	{
		category: 'Regional',
		name: 'Horizon Air',
		image: 'src/assets/americanAirlines.png',
		favorite: false,
	},
	{
		category: 'Regional',
		name: 'JSX',
		image: 'src/assets/americanAirlines.png',
		favorite: false,
	},
	{
		category: 'Regional',
		name: 'Mesa Airlines',
		image: 'src/assets/americanAirlines.png',
		favorite: false,
	},
	{
		category: 'Regional',
		name: 'Peninsula Airways',
		image: 'src/assets/americanAirlines.png',
		favorite: false,
	},
	{
		category: 'Regional',
		name: 'Piedmont',
		image: 'src/assets/americanAirlines.png',
		favorite: false,
	},
	{
		category: 'Regional',
		name: 'PSA Airlines',
		image: 'src/assets/americanAirlines.png',
		favorite: false,
	},
	{
		category: 'Regional',
		name: 'Republic Airways',
		image: 'src/assets/americanAirlines.png',
		favorite: false,
	},
	{
		category: 'Regional',
		name: 'Skywest Airlines',
		image: 'src/assets/americanAirlines.png',
		favorite: false,
	},
]
export { airlines, letters, states, countries, companies }
